on: [push, pull_request]
name: Formatting
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Check Rust formatting
        run: cargo fmt --verbose --manifest-path src/android-simd/Cargo.toml -- --check
